{% set version = "6.4" %}

package:
  name: windows-default-manifest
  version: {{ version }}

source:
  git_url: https://sourceware.org/git/cygwin-apps/windows-default-manifest.git
  git_rev: release-{{ version.replace(".", "_") }}

build:
  number: 6

outputs:
  - name: mingw-w64-ucrt-x86_64-windows-default-manifest
    script: install.sh
    build:
      noarch: generic
    requirements:
      build:
        - make
      host:
      run:
        - __unix   # [unix]
        - __win    # [win]
      run_constrained:
        - m2w64-sysroot_win-64 >=12

    test:
      commands:
        - echo "hello"

about:
  home: https://cygwin.com/
  summary: 'windows-default-manifest - The manifest each executable has to be linked against since Windows 8.1'
  license: FSFAP
  license_file:
    - COPYING


extra:
  recipe-maintainers:
    - isuruf
